name: Run Robot Framework Tests

on:
  push:
    branches: [ "**" ]         # Triggers on push to any branch
  pull_request:
    branches: [ "**" ]         # Triggers on PR to any branch

jobs:
  robot-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install robotframework

      - name: Run Robot Framework tests
        run: |
          robot IntegrationTests/

      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-output
          path: |
            IntegrationTests/savedData/
            IntegrationTests/mocks/sensor_data.json